version: "3.4"
services:
    nginx:
        build:
            context: ../
            dockerfile: $PWD/docker/nginx/Dockerfile
        volumes:
            - ../:/var/www/html
        ports:
            - 8080:80
    php:
        build:
            context: ../
            dockerfile: $PWD/docker/php/Dockerfile
        user: ${USERID}:${GROUPID}
        volumes:
            - ../:/var/www/html
            - $COMPOSER_HOME:/.composer/
    database:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=homeworkx
            - MYSQL_PASSWORD=homeworkx
            - MYSQL_USER=homeworkx
            - MYSQL_DATABASE=homeworkx
    adminer:
        image: adminer